site_name:        Maker.jl
repo_url:         https://github.com/tshort/Maker.jl
site_description: A make-like system for data analysis
site_author:      Tom Short

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Lapidary.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Maker: index.md
- Documentation:
  - Example: introduction.md
  - API: api.md
  - make: make.md
  - Targets: targets.md
  - Utilities: utilities.md
  - Terminology: terminology.md
  - Internals: internals.md
- About:
  - Release notes: ../../NEWS.md
  - License: ../../LICENSE.md
